apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: colour-translator
  template:
    metadata:
      labels:
        app: colour-translator
    spec:
      containers:
      - image: agray998/helm-demo-app:{{ .Values.version }}
        imagePullPolicy: Always
        name: colour-translator
        env:
        - name: PORT
          value: {{ .Values.port | quote }}
        ports:
        - containerPort: {{ .Values.port }}
