apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}.colour-translator.app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}.colour-translator.app
    spec:
      containers:
      - image: {{ printf "agray998/helm-demo-app:v%s" .Chart.AppVersion }}
        imagePullPolicy: Always
        name: colour-translator
        env:
        - name: PORT
          value: {{ .Values.port | quote }}
        ports:
        - containerPort: {{ .Values.port }}
